-- Official 2627 LZV calendar — generated by scripts/import-lzv-calendar.mjs
-- Source: LZV's own iCalendar feed. Run in the Supabase SQL editor (anon key cannot write to games).
-- 21 fixtures: 11 home, 10 away.
-- Scores are left null; the weekly sync-lzv job fills them.
--
-- Re-runnable: refreshes the mutable columns on an id clash and never touches home_score/away_score.
-- NOTE: a rescheduled match changes game_date, which changes the id, so re-importing it would create a
-- SECOND row and orphan every RSVP (attendance/player_stats/guest_players/motm_votes all FK to game_id).
-- Move a fixture by updating game_date/game_time on the EXISTING row instead. See CALENDAR-IMPORT.md.

begin;

insert into games (id, season_slug, opponent, game_date, game_time, location, title) values
  ('2627-2026-09-06-2100-vt-09', '2627', 'VT 09', '2026-09-06', '21:00:00', 'Winketkaai Mechelen', 'VT 09 vs K. Caracrew SK'),
  ('2627-2026-09-24-2100-vv-schemerboyz', '2627', 'VV Schemerboyz', '2026-09-24', '21:00:00', 'Winketkaai Mechelen', 'K. Caracrew SK vs VV Schemerboyz'),
  ('2627-2026-10-08-2100-oranje-duivels', '2627', 'Oranje Duivels', '2026-10-08', '21:00:00', 'Winketkaai Mechelen', 'K. Caracrew SK vs Oranje Duivels'),
  ('2627-2026-10-22-2100-jan-breydel', '2627', 'Jan Breydel', '2026-10-22', '21:00:00', 'Winketkaai Mechelen', 'K. Caracrew SK vs Jan Breydel'),
  ('2627-2026-11-05-2100-zvc-tigers', '2627', 'ZVC Tigers', '2026-11-05', '21:00:00', 'Winketkaai Mechelen', 'K. Caracrew SK vs ZVC Tigers'),
  ('2627-2026-11-08-1800-vv-schemerboyz', '2627', 'VV Schemerboyz', '2026-11-08', '18:00:00', 'IHAM Mechelen', 'VV Schemerboyz vs K. Caracrew SK'),
  ('2627-2026-11-19-2100-wille-ma-ni-kunne', '2627', 'Wille ma ni kunne', '2026-11-19', '21:00:00', 'Winketkaai Mechelen', 'K. Caracrew SK vs Wille ma ni kunne'),
  ('2627-2026-11-23-2100-jan-breydel', '2627', 'Jan Breydel', '2026-11-23', '21:00:00', 'Heiveld St-Katelijne-Waver', 'Jan Breydel vs K. Caracrew SK'),
  ('2627-2026-12-03-2100-de-karpervissers', '2627', 'De Karpervissers', '2026-12-03', '21:00:00', 'Winketkaai Mechelen', 'K. Caracrew SK vs De Karpervissers'),
  ('2627-2026-12-17-2100-04united', '2627', '04United', '2026-12-17', '21:00:00', 'Winketkaai Mechelen', 'K. Caracrew SK vs 04United'),
  ('2627-2027-01-05-1900-oranje-duivels', '2627', 'Oranje Duivels', '2027-01-05', '19:00:00', 'Kouter Leest', 'Oranje Duivels vs K. Caracrew SK'),
  ('2627-2027-01-14-2100-fc-tripel', '2627', 'FC Tripel', '2027-01-14', '21:00:00', 'Winketkaai Mechelen', 'K. Caracrew SK vs FC Tripel'),
  ('2627-2027-01-28-2100-bankzitters-united', '2627', 'Bankzitters United', '2027-01-28', '21:00:00', 'Winketkaai Mechelen', 'K. Caracrew SK vs Bankzitters United'),
  ('2627-2027-02-13-1900-de-karpervissers', '2627', 'De Karpervissers', '2027-02-13', '19:00:00', 'Kouter Leest', 'De Karpervissers vs K. Caracrew SK'),
  ('2627-2027-02-25-2100-vt-09', '2627', 'VT 09', '2027-02-25', '21:00:00', 'Winketkaai Mechelen', 'K. Caracrew SK vs VT 09'),
  ('2627-2027-03-11-2100-knallende-knapen', '2627', 'Knallende Knapen', '2027-03-11', '21:00:00', 'Winketkaai Mechelen', 'K. Caracrew SK vs Knallende Knapen'),
  ('2627-2027-03-27-1930-knallende-knapen', '2627', 'Knallende Knapen', '2027-03-27', '19:30:00', 'SportCube Eppegem', 'Knallende Knapen vs K. Caracrew SK'),
  ('2627-2027-04-14-2200-wille-ma-ni-kunne', '2627', 'Wille ma ni kunne', '2027-04-14', '22:00:00', 'SportCube Eppegem', 'Wille ma ni kunne vs K. Caracrew SK'),
  ('2627-2027-04-24-1930-fc-tripel', '2627', 'FC Tripel', '2027-04-24', '19:30:00', 'Winketkaai Mechelen', 'FC Tripel vs K. Caracrew SK'),
  ('2627-2027-05-04-2100-zvc-tigers', '2627', 'ZVC Tigers', '2027-05-04', '21:00:00', 'Heiveld St-Katelijne-Waver', 'ZVC Tigers vs K. Caracrew SK'),
  ('2627-2027-05-09-2000-04united', '2627', '04United', '2027-05-09', '20:00:00', 'IHAM Mechelen', '04United vs K. Caracrew SK')
on conflict (id) do update set
  opponent  = excluded.opponent,
  game_time = excluded.game_time,
  location  = excluded.location,
  title     = excluded.title;

commit;

-- Verification: expect 21 fixtures, 0 missing a time/location, and 0 whose title omits the team.
select
  (select count(*) from games where season_slug = '2627')                        as fixtures,
  (select count(*) from games where season_slug = '2627' and game_time is null)  as missing_time,
  (select count(*) from games where season_slug = '2627' and location is null)   as missing_location,
  (select count(*) from games where season_slug = '2627'
     and title !~* 'caracrew')                                                                     as title_without_team,
  (select min(game_date) from games where season_slug = '2627')                  as first_game,
  (select max(game_date) from games where season_slug = '2627')                  as last_game;
