/** Per-event revision tracking for the generated fixture feeds.
 *
 * RFC 5545 says a published event that changes should carry a higher `SEQUENCE` and a fresh
 * `LAST-MODIFIED`; a client is entitled to ignore an "update" that claims to be the same revision.
 * Most subscription clients replace events by UID and never look, but the ones that do look were
 * left with no way to tell that a kickoff had moved — the feed shipped no SEQUENCE at all, and its
 * `DTSTAMP` was pinned to the latest fixture DATE, so it stayed byte-identical when a time changed.
 *
 * The awkward part is that SEQUENCE must be **monotonic**: a content hash would go down as often as
 * up, and a client that honours SEQUENCE would then discard a real change. So the previous revision
 * has to come from somewhere. It comes from the previously generated feed itself, which is committed
 * to the repo and therefore present in a CI checkout — for each UID we compare the new event body
 * against the old one and only bump when it actually differs.
 *
 * That also keeps the property the old `feedStamp()` hack existed to protect: an unchanged fixture
 * re-renders byte-for-byte, so a scheduled regen produces no diff and no commit.
 */

import { unfoldIcs } from "./lzvCalendar.js";

/** The three fields this module generates. Rendered separately, never part of a body comparison. */
const REVISION_FIELDS = ["DTSTAMP", "SEQUENCE", "LAST-MODIFIED"];

/** Excluded from "did this change?": the generated fields, plus UID — which is the match key, so
 *  comparing it would be circular, and it also lets an event carry its UID outside `lines`. */
const NOT_CONTENT = new Set([...REVISION_FIELDS, "UID"]);

function propertyName(line) {
  const cut = line.search(/[;:]/);
  return (cut === -1 ? line : line.slice(0, cut)).toUpperCase();
}

/** The part of an event that decides whether it changed: content lines only. */
export function eventBody(lines) {
  return lines
    .filter((line) => line && !NOT_CONTENT.has(propertyName(line)))
    .join("\n");
}

/** `20260906T203000Z` — RFC 5545 UTC date-time. */
export function icsUtcStamp(date) {
  return new Date(date).toISOString().replace(/[-:]/g, "").replace(/\.\d{3}/, "");
}

/**
 * Index a previously generated feed by UID: `{ sequence, dtstamp, body }` per event.
 *
 * Tolerates a missing/absent file (pass ""), events without a UID (skipped — we'd have nothing to
 * match on) and a non-numeric SEQUENCE (treated as 0), because the first run after this change
 * reads a feed generated by the old code, which had no SEQUENCE lines at all.
 */
export function parseIcsRevisions(text) {
  const revisions = new Map();
  const lines = unfoldIcs(String(text || "")).split(/\r?\n/);
  let current = null;

  for (const raw of lines) {
    const line = raw.trim();
    if (!line) continue;
    if (line === "BEGIN:VEVENT") {
      current = [];
      continue;
    }
    if (line === "END:VEVENT") {
      if (current) {
        const uid = current.find((l) => propertyName(l) === "UID");
        if (uid) {
          const seqLine = current.find((l) => propertyName(l) === "SEQUENCE");
          const stampLine = current.find((l) => propertyName(l) === "DTSTAMP");
          const sequence = Number(seqLine?.slice(seqLine.indexOf(":") + 1));
          revisions.set(uid.slice(uid.indexOf(":") + 1), {
            sequence: Number.isFinite(sequence) && sequence >= 0 ? Math.floor(sequence) : 0,
            dtstamp: stampLine ? stampLine.slice(stampLine.indexOf(":") + 1) : null,
            // A feed written before this module existed carries no SEQUENCE — and its DTSTAMP was
            // the latest fixture DATE, i.e. in the future. Flag it so we re-stamp rather than
            // inherit that, once, on the first versioned run.
            versioned: Boolean(seqLine),
            body: eventBody(current),
          });
        }
      }
      current = null;
      continue;
    }
    if (current && !line.startsWith("BEGIN:") && !line.startsWith("END:")) current.push(line);
  }

  return revisions;
}

/**
 * Stamp each event with the revision it deserves, given the feed we published last time.
 *
 * `events` are `{ uid, lines }` with `lines` holding the event's content properties, unfolded.
 * Returns the same order, each with `sequence` and `dtstamp`:
 *   - unchanged body  → the previous sequence and DTSTAMP, so the render is byte-identical
 *   - changed body    → previous sequence + 1, DTSTAMP/LAST-MODIFIED of `now`
 *   - new UID         → sequence 0, DTSTAMP of `now`
 *
 * A pre-SEQUENCE feed (`reason: "migrated"`) bumps every event to 1 even where the content is
 * identical. That is deliberate, not laziness: the old generator stamped DTSTAMP with the LATEST
 * FIXTURE DATE, so it sits in the future, and RFC 5545 breaks an equal-SEQUENCE tie on DTSTAMP —
 * re-publishing at sequence 0 with an EARLIER stamp is precisely what a strict client discards.
 * One bump clears that ambiguity for good; from the next run on, an unchanged fixture renders
 * byte-for-byte identically and the scheduled job produces no diff.
 *
 * A fixture that leaves the feed and later comes back restarts at 0. That is a real (if unlikely)
 * hole — a client still holding the old event would out-rank it — but the alternative is carrying a
 * graveyard of departed UIDs in the feed forever, which is worse.
 */
export function reviseEvents(events, previousText, now = new Date()) {
  const previous = parseIcsRevisions(previousText);
  const stamp = icsUtcStamp(now);

  return events.map((event) => {
    const body = eventBody(event.lines);
    const prior = previous.get(event.uid);
    if (prior && prior.versioned && prior.body === body && prior.dtstamp) {
      return { ...event, sequence: prior.sequence, dtstamp: prior.dtstamp, reason: "unchanged" };
    }
    if (!prior) return { ...event, sequence: 0, dtstamp: stamp, reason: "new" };
    return {
      ...event,
      sequence: prior.sequence + 1,
      dtstamp: stamp,
      reason: prior.versioned ? "content" : "migrated",
    };
  });
}
